// Code generated by "stringer -type=State"; DO NOT EDIT.

package at

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ATReady-0]
	_ = x[ATError-1]
	_ = x[ATNotice-2]
	_ = x[ATData-3]
	_ = x[ATPrompt-4]
	_ = x[ATEcho-5]
}

const _State_name = "ATReadyATErrorATNoticeATDataATPromptATEcho"

var _State_index = [...]uint8{0, 7, 14, 22, 28, 36, 42}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
