// Code generated by "stringer -type=State"; DO NOT EDIT.

package at

import "strconv"

const _State_name = "ATReadyATErrorATDataATPromptATEchoATNotice"

var _State_index = [...]uint8{0, 7, 14, 20, 28, 34, 42}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
